# Generated by Django 5.0 on 2025-07-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blur_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
